#! /bin/bash

DIR=$(readlink -f $(dirname $0))
pushd $HOME >/dev/null
rm .vim*
ln -sf $DIR .vim
ln -sf $DIR/vimrc .vimrc
popd >/dev/null

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

