#! /bin/bash

DIR=$(readlink -f $(dirname $0))
pushd $HOME >/dev/null
ln -sf $DIR .vim
ln -sf $DIR/vimrc .vimrc
ln -sf $DIR/vimrc-bepo .vimrc-bepo
popd $HOME >/dev/null

[ ! -d $DIR/autoload ] && mkdir $DIR/autoload
echo "update pathogen" && curl -# -o $DIR/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim

PROTO=git
# github.com/Townk/vim-autoclose.git
GIT_URLS="
	github.com/scrooloose/nerdtree.git
	github.com/msanders/snipmate.vim.git
	github.com/vim-scripts/taglist.vim.git
	github.com/tpope/vim-commentary.git
	github.com/mirell/vim-matchit.git
	github.com/tpope/vim-repeat.git
	github.com/tpope/vim-surround.git
"
[ ! -d $DIR/bundle ] && mkdir $DIR/bundle
cd $DIR/bundle
for url in $GIT_URLS; do
    gitdir=${url##*/}
    dir=${gitdir%.git}
    if [ -d  "$dir/.git" ]; then
        cd $dir && echo "update $dir" && git pull; cd ..
    else
        git clone "$PROTO://$url"
    fi
done
